packages:
  - 'docs/**'
  - 'packages/**'
  - 'examples/**'
  - 'playground'
  - 'scripts'
  - 'test/**'
  - '!**/.tmp/**'
options:
  prefer-workspace-packages: true
  strict-peer-dependencies: false
